---
- name: SOFTWRE Installation
  hosts: database
  tasks:
    - name: WEBSERVER INSTALLATION
      yum: name=httpd state=latest 
  
    - name: SERVICE START
      service: name=httpd state=restarted      

