-
  name: Demo
  hosts: webservers 
  become: yes 
  tasks: 
    - name: Ensure Apache installed 
      yum: name=httpd state=present 
    - name: Creates directoy 
      file: path=/var/www/html/ansible state=directory 
    - name: Ensure Apache is running 
      service: name=httpd enabled=yes state=started 
  hosts: dbservers 
  become: yes 
  tasks: 
    - name: Ensure mysql installation
      yum: name=mysql state=present
